sudo: required
services:
  - docker

before_install:
  - docker build -t xinyuwahed/docker-react -f Dockerfile.dev .

script: docker run -e CI=true xinyuwahed/docker-react yarn test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker" #the application name of EBS
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-746510979461"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
